language: php

addons:
  postgresql: "9.4"

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - nightly

install:
    - cd hubble
    - cp .env.travis .env
    - composer install
    - psql -c 'create database hubble;' -U postgres
    - php artisan key:generate
    - php artisan migrate